### PR TITLE
Update create-sarcophagus.md

### PR DESCRIPTION
**Pull request by sethhrbek**
Move encrypted shards / unencrypted shard hashes from arweave bundle to first transaction

### CODE REVIEW

**Comment by sethhrbek** [comment]
@adamgall --

> At most, they'd simply screw themselves out of being able to participate in the unwrapping ceremony (thereby sacrificing their bounty).

This part I don't think is correct. If I understand correctly, during the sarco transfer, an entire new arweave bundle is uploaded to replace the old one (with new arweave TX ID). If this new arweave bundle is faulty, then it sabotages the entire sarcophagus because the updated sarcophagus is pointing to this faulty arweave bundle. All archaeologists could unwrap successfully, but when the recipient goes to download the payload, it would be junked.

The other argument I would make here --- In the proposed updated designs, not only does it solve this problem (limiting the archaeologist's malicious behavior to only messing with their single shard rather than the entire sarcophagus), it also removes the need for the weaver to participate in the transfer process, thus making that step simpler.

If (**big if**) we are able to store the encrypted shards off-chain (each archaeologist could store the ones they care about on disk), then overall I don't think the new design would change the amount of data stored in contract state by a ton. New design:

1. Removes: arch public keys from being stored on sarcophagus
2. Adds: unencrypted shard hashes to be stored on sarcophagus
3. Removes: private keys from being stored during unwrapping
4. Adds: unencrypted shards to be stored during unwrapping

For #4 -- I was using this online tool to estimate how big the unencrypted shards are, using an eth private key as the secret -- maybe this is inaccurate, but if it's close then it doesn't look too bad (~512 chars)
https://iancoleman.io/shamir/

**Comment by adamgall** [comment]
> If I understand correctly, during the sarco transfer, an entire new arweave bundle is uploaded to replace the old one (with new arweave TX ID).

Why does that need to be the case? Just 1 new encrypted shard needs to be uploaded to Arweave.

**Comment by sethhrbek** [comment]
@adamgall -- ah ok -- so were you thinking that there would be multiple arweave TX IDs on any given sarcophagus? One TX for the file, then other TX IDs for each shard?

**Comment by adamgall** [comment]
During the creation process just one Arweave TX to hold everything.

But then during any given transfer event, a new TX for the new shard.

Then it would just be up to the client to download all the transactions' data and selectively "replace" what they need to out of the original dataset, with new shards from transfers.

**Comment by adamgall** [comment]
Regarding the rest of your original rebuttal, I have strong feelings that the "statelessness" of an archaeologist is something that we attempt to defend. I really don't like the concept of archaeologists being responsible for storing their own secrets completely independently. It's easy for a consumer-level arch to backup a seed phrase. it's not easy for a consumer-level arch to backup a changing filesystem of super important data.

**Comment by sethhrbek** [comment]
One other scenario to consider:

What happens if Archaeologist uploads a Bullshit shard to arweave during transfer?

1. New archaeologist uploads to sarcophagus:
a. Their public key 
b. The new (bad) arweave TX ID

2. During unwrapping, archaeologist:
a. Provides correct private key

Wouldn't the archaeologist get paid since their private key is correct? But then the arweave shard is junk, so they *should not* have gotten paid.

**Comment by sethhrbek** [comment]
This issue from last comment can be mitigated by original arch signing off on the new archaeologist's arweave TX ID. They could collude to upload bad data, but this would help a little.

If we needed to close this hole, we could do a hybrid approach where encrypted shards are still uploaded to arweave, but the unwrapping must have arch's unencrypted shard submitted rather than the private key.

**Comment by adamgall** [comment]
Yes, you bring up valid points.

> If we needed to close this hole, we could do a hybrid approach where encrypted shards are still uploaded to arweave, but the unwrapping must have arch's unencrypted shard submitted rather than the private key (in this scenario the unencrypted shard hashes would be stored on-chain for verification purposes).

This seems interesting.

Another approach is to go with the option where Original Arch has to sign off on the Arweave data, which would require both Arch's colluding (or one entity running two archs...); but also just give the embalmer the option to disallow arch transfers on the sarcophagus they're creating, if they don't want to take that risk. "Risk-averse" archaeologists could always choose to pass on jobs that disallow transfers, for example.

**Comment by sethhrbek** [comment]
Giving option to disallow transfers is a great idea.

I'd like to get a better understanding of the TX cost differential between:
1. Using pub key / priv keys on a sarcophagus VS.
2. Using unencrypted shard hashes / unencrypted shards. 
 
If the cost for #2 is higher by a substantial amount, then probably better to stick with #1 (and accept the low arch collusion risk for sarcos that allow transfers). We will proceed with #1 and then do some TX cost benchmarking on #2 once contracts are in a good enough place to do that.

**Pull request closed without merging**
